# @package eval.tofu.metrics.forget_Q_A_PARA_ROUGE
defaults:
  - ../../data/datasets@datasets: TOFU_QA_forget_para
  - ../../collator@collators: DataCollatorForSupervisedDatasetwithIndex
  - ../../generation@generation_args: default
  
  # ^ get default dataset and generation config information

handler: rouge
rouge_type: rougeL_recall
batch_size: 32

datasets: # override as needed
  TOFU_QA_forget_para:
    args:
      hf_args:
        name: ${eval.tofu.forget_split}_perturbed
      predict_with_generate: True
collators:
  DataCollatorForSupervisedDataset: 
    args:
      padding_side: left
