# @package eval.muse.metrics.forget_minKpc_neg_logprob
defaults:
  - ../../data/datasets@datasets: MUSE_forget_privleak
  - ../../collator@collators: DataCollatorForSupervisedDatasetwithIndex
handler: minKpc_negative_logprob
batch_size: 8
percentile_K: 40

datasets:
  MUSE_forget_privleak:
    args:
      hf_args:
        path: muse-bench/MUSE-${eval.muse.data_split}